### ISSUE TITLE
Input TODO

### ISSUE THREAD

**Issue by huacnlee** [huacnlee/gpui-component#27]
- [x] Double Click to select word, triple click to select line.
- [x] Cut may over the range, the end offset sometime is more than 1 char.
- [x] The selected text foreground in Dark mode need to a better color.
- [ ] ContextMenu to let user copy, cut, paste.
- [x] Keep showing the cursor when press key.
- [x] Overflow scroll
- [x] Undo histories
- [x] Eye button to toggle password mask
